### ISSUE TITLE
Implementar la condició de fi de joc

### ISSUE THREAD

**Issue by Alesan** [EnginyeriaSofwareUB/ES2017A3#12]
Fer que el joc acabi una volta cada personatge ha fet un torn.
Quan el joc acaba el programa es tanca.
Com que tenim 4 personatges el joc acabarà al final del quart torn.

Temps estimat: 12h
Temps de realització: 10h

**Comment by Zehalla** [comment]
Afegida la classe encarregada de controlar si el joc ha acabat el joc: 2h
Falta Integració.

**Comment by Zehalla** [comment]
Integracio feta: 1h

Temps estimat: 12h Temps real: 3h
