### ISSUE TITLE
Esborrar les branques antigues del GitHub

### ISSUE THREAD

**Issue by Zehalla** [EnginyeriaSofwareUB/ES2017A3#128]

**Comment by fwilliams96** [comment]
Hecho para las mías.

**Comment by Alesan** [comment]
Ídem

**Comment by Zehalla** [comment]
Buen trabajo again. Casi todas las ramas han sido borradas, excepto las de Miriam.

**Comment by Zehalla** [comment]
Es torna a obrir aquesta tasca per a l'Sprint 5. Res de deixar branques acabades tirades pel Git.

**Comment by Zehalla** [comment]
Totes esborrades, git net.
