### ISSUE TITLE
Outline/silueta de color diferent pels tòtems de cada equip

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#135]
Outline/silueta de color diferent pels tòtems de cada equip: un equip de color vermell i l'altre blau, per exemple, seguint la lògica de la pantalla de selecció d'equips, on hi ha un equip de cada color. Outline especial (per exemple groc pel tòtem que té torn).

Temps estimat: 6h
Tiempo real:6h

**Comment by ae11112** [comment]
Alguns tòtems/mòduls surten sense outline, convindria corregir-ho.

**Comment by Alesan** [comment]
Corregido.
