### ISSUE TITLE
Efecte visual i sonor quan mor un tòtem

### ISSUE THREAD

**Issue by gcasasbe7** [EnginyeriaSofwareUB/ES2017A3#136]
Addició de l'efecte del tòtem quan rep un impacte que el fereix (Albert).
Addició de l'efecte del tòtem quan mor per fi de vida al mapa (Albert).
Addició de l'efecte quan mor per caiguda del mapa (Albert).
Integració dels efectes quan succeeixen les morts en el joc (Aleix).

Temps estimat (disseny): 3h
Temps de realització (disseny): 3h
Temps estimat (integració): 3h

Resultat visual:
![damage](https://user-images.githubusercontent.com/17698746/33481772-3a00ab96-d696-11e7-988d-bdb9b112bc32.png)
![death](https://user-images.githubusercontent.com/17698746/33481773-3a19d350-d696-11e7-82bb-04cab8f7f970.png)
![falldeath](https://user-images.githubusercontent.com/17698746/33481774-3a30f940-d696-11e7-8de3-bdc16a7f1359.png)

**Comment by ae11112** [comment]
Part de disseny feta (Totems/TotemEffects), falta integrar per codi.

**Comment by Zehalla** [comment]
Afegides les animacions

Temps emprat: 3h
