### ISSUE TITLE
Millores UI de la pantalla de joc

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#139]
- Mostrar el nom de l'equip que té torn (vermell o blau, per exemple).
- Mostrar passes restants en temps real.
- Treure camp de diners (no s'usa).
- Millorar resolució.

Temps estimat: 4h
Temps realització: 4h

**Comment by gcasasbe7** [comment]
Disseny de les noves addicions: 1h
