### ISSUE TITLE
Funcionalitat de barra de vida sobre els personatges actualitzada dinàmicament

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#43]
Ús de la barra de vida dissenyada present a l'escena ProgressBar. Quan s'alteri el valor de vida de la classe tòtem també s'ha de variar la barra de vida, que ha de seguir el personatge en tot moment, i mostrar-se completa quan el valor numèric de vida és el màxim fixat.

Temps estimat: 5h

**Comment by kurimin** [comment]
When one player is near to another and this one attacks (throw a bomb), the bomb explodes and it deals damage to both of them.
