### ISSUE TITLE
Fer que el tòtem mori en caure per sota de l'escenari

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#46]
Cal partir de l'issue #42 (mort de tòtem) i posar 4 volums (sota, sobre, a dreta i esquerra) de l'escena que eliminin qualsevol entitat que la toqui (en el cas del personatge processant la funcionalitat de morir).

Temps estimat: 8h

**Comment by Zehalla** [comment]
S'ha trobat una forma alternativa de establir els límits sense utilitzar volums.
Necessita d'una segona càmera que delimita els límits del mapa i que tots els objectes tinguin un sprite renderer per tal que el nou mòdul funcioni.

Temps real: 3h
