### ISSUE TITLE
Generació de caixes d'objectes i físiques/destructibilitat en rebre projectils

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#51]
Funcionalitat de caixes que es generin cada X torns pel mapa , físiques en rebre projectils i trencar-se si l'impacte venç la seva resistència. Preparar el codi perquè en un futur això pugui alliberar un objecte (de moment que sigui una esfera o mesh temporal).

Temps estimat: 7h

Temps realització: 5h

**Comment by fwilliams96** [comment]
S'ha aconseguit fer que la coordenada en l'eix X variés segons el tamany de la plataforma (illes) de l'escena, per tal de variar la posició on es generen les caixes. Això s'ha aconseguit amb un algorisme finalment en comptes de crear un rectangle BoxCollider que envoltés les illes. També s'ha canviat el prefab de la box pel de l'Albert.
