### ISSUE TITLE
Nova condició de fi de joc: s'acaba quan tots els personatges d'un jugador morin

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#52]
Nova condició de fi de joc: s'acaba quan tots els personatges d'un jugador morin; guanya l'altre jugador (porta a la pantalla de fi de partida, issue #48) i requereix que ja els personatges puguin morir (issue #42).

Temps estimat: 4h

**Comment by Zehalla** [comment]
Fet: 2h 30min aprox.
