### ISSUE TITLE
Disseny de les barres de vida dels personatges

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#8]
Cada barra de vida de cada jugador serà d'un color diferent (de moment s'exporten a Unity però sense aplicar-les als personatges).
Temps estimat: 7h
Temps de realització: 6h

Resultat visual:
![lifebar](https://user-images.githubusercontent.com/17698746/31673210-eaf654d8-b35e-11e7-8ee7-4ae027c20f19.png)

**Comment by gcasasbe7** [comment]
Cada nom i barra de vida de cada jugador serà d'un color diferent
