### ISSUE TITLE
Limitar distància de fletxa per disparar

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#87]
Limitar distància de fletxa per disparar, que no pugui estirar-se per tota la pantalla.

Temps estimat: 1h

**Comment by Zehalla** [comment]
A més s'ha de limitar la longitud total de la fletcha.

**Comment by Zehalla** [comment]
En @gcasasbe7 farà el disseny de la nova fletxa de dispar.

**Comment by ae11112** [comment]
Aquesta tasca es portava arrossegant des de feia varis Sprints i no estava feta al moment d'acabar el darrer Sprint, així que s'ha cancel·lat, i tenint en compte que la seva branca portava 24 dies sense actualitzacions s'ha eliminat també la seva branca per complir amb la tasca d'eliminar branques inactives.

**Comment by ae11112** [comment]
Veient que finalment s'ha fet la tasca, ha estat restaurada a la documentació.
