### ISSUE TITLE
Fer que el personatge pugui portar varis d'objectes

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#90]
Fer que el personatge pugui portar varis d'objectes. La majoria d'objectes no es poden portar simultàniament, excepte amb l'objecte defensiu (escut), amb el que pots portar equipat un altre.

Fer classe objecte base i subclasses d'objectes (atac, curatiu, desplaçament i defensiu).

Temps estimat: 8h

**Comment by Zehalla** [comment]
Creades les classes abstractes Item i les seves subclasses: HealingItem, AttackItem, DefensiveItem i MovementItem. Temps: 1h

**Comment by Zehalla** [comment]
Adaptar el codi per que funcioni l'Asset d'inventari (Eliminar el que havia fet abans): 2h

**Comment by Zehalla** [comment]
Afegida la Hotbar de InventoryMaster al totem: 1h.

**Comment by ae11112** [comment]
Falta integrar la hotbar.

**Comment by Zehalla** [comment]
La hotbar ja està integrada i funcionant. He assignat els botons Q,W,E als slots de la hotbar.

Temps emprat: 4h
