### ISSUE TITLE
Afegir els objectes que s'agafen del mapa a l'inventari

### ISSUE THREAD

**Issue by ae11112** [EnginyeriaSofwareUB/ES2017A3#97]
Quan s'agafi un objecte ha de crear una cel·la a l'inventari si no existia, o, si ja existia, que incrementi una unitat. Cada objecte ha de tenir un atribut d'icona d'inventari.

Temps estimat: 4h

**Comment by Zehalla** [comment]
N'@Alesan ha fet l'script de quan el totem toqui l'objecte l'item vagi a l'inventari.
